import { Mapping } from "./Mapping"
import { Operation } from "./Operation"
import { Schema } from "./Schema"

export namespace Transaction {
	export const mapping = {
		counterpartType: "value.counterpart.type",
		counterpart: { selector: "value.counterpart", transform: "stringify" },
		counterpartCode: "value.counterpart.code",
		currency: "value.currency",
		amount: { selector: "value.amount", transform: "number" },
		description: "value.description",
		organization: "value.organization",
		accountId: "value.accountId",
		accountName: "value.accountName",
		account: { selector: "value.account", transform: "stringify" },
		accountType: "value.account.type",
		type: "value.type",
		direction: "value.direction",
		id: "value.id",
		referenceSupplier: "value.reference.supplier",
		referenceReference: "value.reference.reference",
		referenceReturnId: "value.reference.returnId",
		referenceEndToEndId: "value.reference.endToEndId",
		posted: "value.posted",
		transacted: "value.transacted",
		by: "value.by",
		actualBalance: { selector: "value.balance.actual", transform: "number" },
		reservedBalance: { selector: "value.balance.reserved", transform: "number" },
		availableBalance: { selector: "value.balance.available", transform: "number" },
		operations: { selector: "value.operations[*]", transform: {
			account: "account",
			currency: "currency",
			changes: { selector: "changes", transform: "array" },
			type: "type",
			transaction: "transaction",
			counter: { selector: "counter", transform: "integer"},
			created: "created",
			signature: "signature",
			previous: "previous",
		}},
		status: "value.status",
		rail: "value.rail",
		railType: "value.rail.type",
		flags: "value.flags",
		oldFlags: "value.oldFlags",
		notes: { selector: "value.notes", transform: "stringify" },
		risk: { selector: "value.risk", transform: "number" },
		state: { selector: "value.state", transform: "stringify" },
	} as const satisfies Mapping
	export type Fields = keyof typeof mapping
	export const schema: Schema<Fields> = [
		{ name: "counterpartType", type: "STRING" },
		{ name: "counterpart", type: "STRING" },
		{ name: "counterpartCode", type: "STRING", mode: "NULLABLE" },
		{ name: "currency", type: "STRING" },
		{ name: "amount", type: "NUMERIC" },
		{ name: "description", type: "STRING" },
		{ name: "organization", type: "STRING" },
		{ name: "accountId", type: "STRING" },
		{ name: "accountName", type: "STRING", mode: "NULLABLE" },
		{ name: "account", type: "STRING" },
		{ name: "accountType", type: "STRING" },
		{ name: "type", type: "STRING", mode: "NULLABLE" },
		{ name: "direction", type: "STRING", mode: "NULLABLE" },
		{ name: "id", type: "STRING" },
		{ name: "referenceSupplier", type: "STRING", mode: "NULLABLE" },
		{ name: "referenceReference", type: "STRING", mode: "NULLABLE" },
		{ name: "referenceReturnId", type: "STRING", mode: "NULLABLE" },
		{ name: "referenceEndToEndId", type: "STRING", mode: "NULLABLE" },
		{ name: "posted", type: "DATETIME" },
		{ name: "transacted", type: "DATETIME", mode: "NULLABLE" },
		{ name: "by", type: "STRING", mode: "NULLABLE" },
		{ name: "actualBalance", type: "NUMERIC" },
		{ name: "reservedBalance", type: "NUMERIC" },
		{ name: "availableBalance", type: "NUMERIC" },
		{ name: "operations", type: "RECORD", mode: "REPEATED", fields: Operation.schema },
		{ name: "status", type: "STRING" },
		{ name: "rail", type: "STRING", mode: "NULLABLE" },
		{ name: "railType", type: "STRING" },
		{ name: "flags", type: "STRING", mode: "REPEATED" },
		{ name: "oldFlags", type: "STRING", mode: "REPEATED" },
		{ name: "notes", type: "STRING", mode: "REPEATED" },
		{ name: "risk", type: "NUMERIC", mode: "NULLABLE" },
		{ name: "state", type: "STRING", mode: "NULLABLE" },
	]
}
