name: "Publish"

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/pax2pay/model-banking

      - name: Install dependencies
        run: cd model-banking && npm install

      - name: Build
        run: cd model-banking && npm run build

      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && cd model-banking && npm publish --dry-run
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
